### ISSUE TITLE
GPU not work when use OpenCL

### ISSUE THREAD

**Issue by smartadpole** [alibaba/MNN#1079]
# 平台:  ubuntu18

# Github版本:` d7fb0ed`

# 编译方式:

```
option(MNN_OPENCL "Enable OpenCL" ON)
option(MNN_OPENGL "Enable OpenGL" OFF)
```
cmake output:    
```
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: x86_64
-- 	Metal: OFF
-- 	OpenCL: ON
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	OpenMP: OFF
-- 	Hidden: TRUE
```

When I use MNN_FORWARD_OPENCL, The CPU is working, while the GPU not.   
shell:   
```
./benchmarkExprModels.out ResNet_100_18 10 3 4
```
output:    
```
Forward type: **OpenCL** thread=4
Can't Find type=3 backend, use 0 instead
```

Why the GPU not work when forward.

**Comment by jxt1234** [comment]
See https://www.yuque.com/mnn/en/faq. 

"Can't use opencl / vulkan in PC
Fastest way to solve:
cmake .. -DMNN_USE_SYSTEM_LIB=true -DMNN_SEP_BUILD=false
Can't find system lib
You can set MNN_USE_SYSTEM_LIB = true , then MNN will use system driver instead of to find it.
Linux System's extra problem
OpenCL / Vulkan use auto register variable. For linux will not direct link it. You can solve this problem by :
1. Set MNN_SEP_BUILD = false.  Make opencl / vulkan info MNN main so.
2. dlopen("libMNN_CL.so") for your main program. See https://github.com/alibaba/MNN/issues/105 .
If you has install opencl / vulkan driver, set MNN_USE_SYSTEM_LIB = true to use your dirver instead of let mnn search the library."

**Comment by smartadpole** [comment]
Thank you. @jxt1234 
 I use `cmake -DMNN_BUILD_BENCHMARK=true -D CMAKE_INSTALL_PREFIX=./install  -D MNN_OPENCL=ON -D MNN_USE_SYSTEM_LIB=ON -D MNN_SEP_BUILD=OFF ..` for build. It work well.

**Comment by siweimaodou** [comment]
@smartadpole 按你这个来了一遍，我这的结果是：
./benchmarkExprModels.out ResNet_100_18 10 3 4
MNN Expr Models benchmark
Forward type: **OpenCL** thread=4
Error for 146
Segmentation fault

你是在ubutu下运行的吧

**Comment by smartadpole** [comment]
是的，在 ubuntu 下，ubuntu 20和ubuntu18测试都正常；
你这个编译没有问题，运行报错很奇怪；看看有没有改过 cmakelist，我的基本每改过； 
@siweimaodou

**Comment by jxt1234** [comment]
更新下再试试吧

**Comment by violet17** [comment]
> # 平台: ubuntu18
> # Github版本:` d7fb0ed`
> # 编译方式:
> ```
> option(MNN_OPENCL "Enable OpenCL" ON)
> option(MNN_OPENGL "Enable OpenGL" OFF)
> ```
> 
> cmake output:
> 
> ```
> -- MNN BUILD INFO:
> -- 	System: Linux
> -- 	Processor: x86_64
> -- 	Metal: OFF
> -- 	OpenCL: ON
> -- 	OpenGL: OFF
> -- 	Vulkan: OFF
> -- 	ARM82: OFF
> -- 	OpenMP: OFF
> -- 	Hidden: TRUE
> ```
> 
> When I use MNN_FORWARD_OPENCL, The CPU is working, while the GPU not.
> shell:
> 
> ```
> ./benchmarkExprModels.out ResNet_100_18 10 3 4
> ```
> 
> output:
> 
> ```
> Forward type: **OpenCL** thread=4
> Can't Find type=3 backend, use 0 instead
> ```
> 
> Why the GPU not work when forward.

我用这个命令：
`sudo apt install ocl-icd-opencl-dev`

然后就好了
