### ISSUE TITLE
I have two crash issue but can't find a reason and solution.

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#1219]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Windows

# Github版本:
# Github Version:
Latest master 

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

Hi,
I'm using MNN on my service but some crashes are reported but I can't find a reason and solution.
First,
```
MNN::CV::ImageProcess::create(MNN::CV::ImageFormat,MNN::CV::ImageFormat,float const *,int,float const *,int,MNN::Tensor const *) [imageprocess.cpp : 54 + 0x3d]
    eip = 0x5cdd7f5d   esp = 0x0c3bf21c   ebp = 0x0c3bf268   ebx = 0x11a702a8
    esi = 0x0c3bf31c   edi = 0x11a70280   eax = 0x0c3bf25c   ecx = 0x00000000
    edx = 0x10dafd28   efl = 0x00010282
    Found by: given as instruction pointer in context
```
My codes below so I think there is no crash point.
```
const float normVals[3] = { 1 / 255.0f, 1 / 255.0f, 1 / 255.0f };
std::shared_ptr<MNN::CV::ImageProcess> pretreat(MNN::CV::ImageProcess::create(format, MNN::CV::RGB, nullptr, 0, normVals, 3));
```
Second,
```
MNN::CV::Matrix::reset() [matrix_cv.cpp : 65 + 0x0]
    eip = 0x63015b4b   esp = 0x1130edd4   ebp = 0x1130ef68   ebx = 0x146626d8
    esi = 0x00000280   edi = 0x18414a20   eax = 0x000001e0   ecx = 0x1130eedc
    edx = 0x1a023020   efl = 0x00010202
    Found by: given as instruction pointer in context
```
I checked Matrix.cpp but there is no doubt things.
I didn't reproduce two issues just reported by user.
Can you check this or give me some idea to fix this?
Thank you.

**Comment by hjchen2** [comment]
Thanks, and sorry for the issues. Please provide the full code so that we could reproduce your crashes. Is that OK?

**Comment by GHLab** [comment]
@hjchen2 Well, I can't share full code by policy but there is no special things with demo and second codes is almost same with https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/MNN/src/UltraFace.cpp I use same model and codes.

**Comment by GHLab** [comment]
@hjchen2 There are no crash log after building MNN without avx. I don't understand there is no avx instruction on that functions. Do you have any thoughts?

**Comment by GHLab** [comment]
@hjchen2 Also, User reported that second crash has been occurred on Rosetta of Apple M1 despite of avx disabled.

**Comment by hzawary** [comment]
Hi,

I'm using UltraFace with MNN for inference, MNN successful build with following environment:

MNN 1.0.0
VS2019
x64
Cmake 3.19.1 interface
Under cmake file change /MT to /MD when MNN_BUILD_SHARED_LIBS = OFF
All options set to OFF, but these:
MNN_SUPPORT_TFLITE_QUAN
MNN_USE_CPP11
MNN_USE_SYSTEM_LIB
MNN_USE_THREAD_POOL

On inference  I'm getting error:
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

When try to build with MNN_BUILD_SHARED_LIBS = ON, everything is ok.

I also trying to build MNN 1.1.0 with MNN_BUILD_SHARED_LIBS = OFF, everything is ok under i7-4770k, but i5-2410M doesn't work, I think because of lack AVX2. Error is:
System.Runtime.InteropServices.SEHException
  HResult=0x80004005
  Message=External component has thrown an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

How to build MNN with lib and /MD for AVX or not?

Regards,
HZ

**Comment by yizhaoyanbo** [comment]
@GHLab 
You can try to delete the following code in MNN/CMakelists.txt, line 304,  to solve the  `Matrix::reset` crash.

```
 target_compile_options(MNNCV PRIVATE -mavx)
```

**Comment by hzawary** [comment]
> @GHLab
> You can try to delete the following code in MNN/CMakelists.txt, line 304, to solve the `Matrix::reset` crash.
> 
> ```
>  target_compile_options(MNNCV PRIVATE -mavx)
> ```

@yizhaoyanbo, thanks for reply, doesn't work, I guess not relevant to avx.

**Comment by GHLab** [comment]
@yizhaoyanbo Already, I did it and resolved reset crash but found one more crash on 'MNNBlitC3ToFloatRGBA'. 
The exception type is 'ILLEGAL_INSTRUCTION'. I guess it's SSE issue but I don't know why.
