### ISSUE TITLE
Jeston Nano 上 GPU 版本报错

### ISSUE THREAD

**Issue by smartadpole** [alibaba/MNN#1265]
# 平台:   Jeston nano
# Github版本: 3ea9dd1
# 编译方式: with opencl

```
cmake -DMNN_BUILD_BENCHMARK=true -DMNN_BUILD_CONVERTER=true -D CMAKE_INSTALL_PREFIX=./install -DMNN_BUILD_BENCHMARK=true -D MNN_OPENCL=ON -D MNN_USE_SYSTEM_LIB=ON -D MNN_SEP_BUILD=OFF ..
```

# 编译日志: 正常

# 测试 benchmark
cpu 测试结果正常： `./benchmarkExprModels.out ShuffleNet_100_4 10 0 4`
gpu 测试异常： `./benchmarkExprModels.out ShuffleNet_100_4 10 3 4`   
 之前改过一个版本——[#1155](https://github.com/alibaba/MNN/issues/1155)，但是仍然报错     
```
MNN Expr Models benchmark
Forward type: **OpenCL** thread=4
ERROR CODE : -1001 
Can't Find type=3 backend, use 0 instead
ERROR CODE : -1001 
Can't Find type=3 backend, use 0 instead
[ - ] ShuffleNet_100_4            max =   31.765ms  min =   30.323ms  avg =   30.690ms
```
怎么调用 jestion nano 的 gpu

**Comment by xiaochus** [comment]
same `ERROR CODE : -1001 ` error with opencl build on my Raspberry Pi 4B device.

**Comment by leemengxing** [comment]
same errorcode：-1001 with ubuntu18.04

**Comment by leemengxing** [comment]
我感觉还是编译问题，因为没有libMNN_CL.so,只有libMNN.so。

**Comment by smartadpole** [comment]
> 我感觉还是编译问题，因为没有libMNN_CL.so,只有libMNN.so。

应该不是，因为使用了 `MNN_SEP_BUILD=OFF` 选项，所以 libMNN_CL.so 和 libMNN.so 会合二为一；

**Comment by leemengxing** [comment]
官方文档的版本太老了，只有基础功能编译，其他都要靠摸索。

**Comment by leemengxing** [comment]
@smartadpole 重新拉取代码编译，已经解决这个问题。
![2021-02-18 14-21-22屏幕截图](https://user-images.githubusercontent.com/24696984/108314281-9aeb4180-71f4-11eb-97c8-1f3da95b70f9.png)

**Comment by msx23p** [comment]
For me this problem is not solved, as I just get the same errors on a aarch64 linux with adreno gpu and installed opencl driver:

`Forward type: **OpenCL** thread=4
ERROR CODE : -1001 
Can't Find type=3 backend, use 0 instead
ERROR CODE : -1001 
Can't Find type=3 backend, use 0 instead`

Does anyone have an idea how to fix this or at least how to debug it?

Unfortunately the following fix in the faq does not help:
`Fastest way to solve:
cmake .. -DMNN_USE_SYSTEM_LIB=true -DMNN_SEP_BUILD=false
Can't find system lib
You can set MNN_USE_SYSTEM_LIB = true , then MNN will use system driver instead of to find it.
Linux System's extra problem
OpenCL / Vulkan use auto register variable. For linux will not direct link it. You can solve this problem by :
1. Set MNN_SEP_BUILD = false.  Make opencl / vulkan info MNN main so.
2. dlopen("libMNN_CL.so") for your main program. See https://github.com/alibaba/MNN/issues/105 .
If you has install opencl / vulkan driver, set MNN_USE_SYSTEM_LIB = true to use your dirver instead of let mnn search the library.`

and the following which was proposed in another thread does also not help:
`Currently on linux the code will not be automatic executed. Please dlopen the libMNN_CL.so in your main code, and link -dl , like this:
#inlcude<dlfcn.h>
int main() {
auto handle = dlopen("libMNN_CL.so", RTLD_NOW);

/Run MNN/
}`
