### ISSUE TITLE
Compile On Windows with Mingw Failed

### ISSUE THREAD

**Issue by Ext4FAT** [alibaba/MNN#266]
I have run  `generate.ps1` in `schema`, configure cmake and generate makefile, but when compile whith  the following error occured
```
$ mingw32-make.exe

*** done ***

[  0%] Built target MNN_SCHEMA

[  0%] Building C object CMakeFiles/MNN.dir/source/core/MNNMemoryUtils.c.obj

gcc.exe: error: /wd4244: No such file or directory

gcc.exe: error: /wd4146: No such file or directory

gcc.exe: error: /wd4018: No such file or directory

gcc.exe: error: /wd4267: No such file or directory

gcc.exe: error: /wd4996: No such file or directory

gcc.exe: error: /wd4081: No such file or directory

CMakeFiles\MNN.dir\build.make:62: recipe for target 

'CMakeFiles/MNN.dir/source/core/MNNMemoryUtils.c.obj' failed

mingw32-make[2]: *** [CMakeFiles/MNN.dir/source/core/MNNMemoryUtils.c.obj] Error 1

CMakeFiles\Makefile2:71: recipe for target 'CMakeFiles/MNN.dir/all' failed

mingw32-make[1]: *** [CMakeFiles/MNN.dir/all] Error 2

Makefile:128: recipe for target 'all' failed

mingw32-make: *** [all] Error 2
```

**Comment by jimdinunzio** [comment]
Hi,
I am also working with MINGW64 and was able to build an older version but with the latest version 0.2.0.9 I have had to modify all the CMakeLists.txt files to change the following:

if (MSVC ~~OR WIN32~~)
... usually there are MSVC compliler switches here like /wd4018 which do not work on MINGW which uses GCC/G++
else
... here is the correct code for MINGW and POSIX compliant compilers
endif

I am still having problems with the link of support libraries such as libonnx, which are getting linker errors of undefined protobuf functions. But I'm still working on it.

I recommend to the authors that you put if (MSVC) in its own separate block because the MS compiler takes different syntax.
e.g.
if (WIN32)
   if (MSVC)
       ... do MSVC stuff
   else()
       ... do MINGW / Windows POSIX / GCC stuff
   endif()
   ... do pure LINUX stuff
endif()

Let me know what you think.

Jim DiNunzio

**Comment by ystsaan** [comment]
using cmake-gui and visual studio solves the problem
