### ISSUE TITLE
debian系统下mnnquant量化出错：

### ISSUE THREAD

**Issue by LimingA1** [alibaba/MNN#2849]
debian系统下mnnquant量化出错：
terminate called after throwing an instance of 'std::length_error'
  what():  cannot create std::vector larger than max_size()
Aborted

**Comment by Nithinholalkere** [comment]
could you provide the argument passing for Python based quantization ? Since I facing an issue with version incapitability between protobuffer library and MNN library

python3 mnnquant.py /home/kpit/Incab
in_sensing_fy_24_25/Nithin/qnx/src/inferenceAppNew/inceptionV3_fp_32.mnn /home/kpit/Incabin_sensing_fy_24_25/Nithin/qnx/src/inferenceAp
pOll/test.mnn /home/kpit/Incabin_sensing_fy_24_25/Nithin/qnx/src/imageInputConfig.json
Traceback (most recent call last):
  File "/home/kpit/Incabin_sensing_fy_24_25/Nithin/Alibaba_MNN/MNN/pymnn/pip_package/MNN/tools/mnnquant.py", line 8, in <module>
    import _tools as Tools
ImportError: /home/kpit/anaconda3/lib/python3.11/site-packages/MNN-2.8.3-py3.11-linux-x86_64.egg/_tools.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN6google8protobuf8internal14ArenaStringPtr3SetENS2_15NonEmptyDefaultERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS0_5ArenaE
