### ISSUE TITLE
The quantized model's inference speed is slow.

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#663]
Hi,
I created quantized model but inference speed is slow.
Non-quantized model's inference duration time is about 10ms but it was 50ms.
As I know, quantization model is 2-3x speedup.
Is there different way when using quantized model on MNN?

I added tested quantized model to here https://github.com/GHLab/deep-head-pose-lite-mnn

**Comment by jxt1234** [comment]
Do you test it in x86? MNN only optimize quantized model for ARM.
For mobile (ARM v7a and ARM v8) , the quantized model usually will only speed up 10% - 30% . Because MNN's float and int8 conv are both optimized. Quantization in ARM's SIMD don't run faster than float.

For the case quantization model 2-3x speedup, the reason is the float part is not optimized well.

**Comment by GHLab** [comment]
@jxt1234 Thank you for quick reply. Sorry I did't know that. I tested it on macos. I will test again  on mobile. 
Thank you!

**Comment by curehabit** [comment]
> Do you test it in x86? MNN only optimize quantized model for ARM.
> For mobile (ARM v7a and ARM v8) , the quantized model usually will only speed up 10% - 30% . Because MNN's float and int8 conv are both optimized. Quantization in ARM's SIMD don't run faster than float.
> 
> For the case quantization model 2-3x speedup, the reason is the float part is not optimized well.

I test my quantized model in ARMv8(845, android), and its inference time is about 4s. But non-quantized model is only 3.5s.
