### ISSUE TITLE
Android Demo App crashed

### ISSUE THREAD

**Issue by jadenwjh** [alibaba/MNN#843]
My workflow was to build the project/android then build demo/android, as suggested here:
https://github.com/alibaba/MNN/issues/662

The error I had when I was building project/android was:
> Could not find com.android.tools.build:aapt2:3.2.1-4818971

And the error I had when I was building demo/android was:
>  ninja: error: '../../../../libs/armeabi-v7a/libMNN.so', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libmnncore.so', missing and no known rule to make it

After making some changes to the build.gradle file I have successfully built project/android, as seen here:
<img width="2013" alt="Screen Shot 2020-05-29 at 19 49 12 PM" src="https://user-images.githubusercontent.com/62279469/83257646-614a5480-a1e7-11ea-8ca2-6f5f3f97fa55.png">

Then I tried to built the demo app, which seems to build well, after making some changes to the CMakeLists.txt file, as seen here:
<img width="2019" alt="Screen Shot 2020-05-29 at 19 51 37 PM" src="https://user-images.githubusercontent.com/62279469/83257684-7626e800-a1e7-11ea-8138-a11991a91630.png">

However, when I tried to launch the app, it crashes and I had 3 warnings:

1) Cannot build selected target ABI: x86, no suitable splits configured: armeabi-v7a;
2) ABIs [x86] set by 'android.injected.build.abi' gradle flag contained 'X86' not targeted by this project.
3) Targeted device ABI or comma-delimited ABIs [x86] is not one of []. Nothing to build.

<img width="2015" alt="Screen Shot 2020-05-29 at 19 53 28 PM" src="https://user-images.githubusercontent.com/62279469/83257717-84750400-a1e7-11ea-8010-f1d429c634e2.png">

Is there something I am doing wrong or missing?

**Comment by yehorchankov** [comment]
Hello there! This type of error suggests, that you use x86-based device (which is because you use Android emulator on your computer). But your project is not configured properly for x86, only for arm-based 32 bit devices (as suggested by this: `no suitable splits configured: armeabi-v7a`).

To configure your project, create folders:
`MNN/demo/android/app/src/main/jniLibs/arm64-v8a`
`MNN/demo/android/app/src/main/jniLibs/armeabi-v7a`
`MNN/demo/android/app/src/main/jniLibs/x86`
`MNN/demo/android/app/src/main/jniLibs/x86_64`
And in each one place libMNN.so file for the particular architecture.

In `MNN/demo/android/build.gradle update the following lines:
```
android {

buildTypes {
        defaultConfig {
       // something here
       externalNativeBuild {
            cmake {
                 // something here
                abiFilters 'arm64-v8a', 'armeabi-v7a'
            }
        
        debug {
            ndk {
                abiFilters 'arm64-v8a', 'armeabi-v7a' 
            }
        }
      // whatever goes next
```

Note, that I use only two splits `arm64-v8a`, `armeabi-v7a`, but you can also add `x86` and `x86_64` to the lists.

Rebuild your project and run again. 

Also, I would strongly recommend you to use physical android device for debugging if you have any.

**Comment by dandingol03** [comment]
i met the same error, have you fix that ? @jadenwjh

**Comment by wangzhaode** [comment]
https://github.com/alibaba/MNN/issues/1080

**Comment by wangzhaode** [comment]
DEMO已更新：https://github.com/alibaba/MNN/pull/2244
